# These properties are active when running the application under any and all profiles.
application.name=Tweet API
application.version=1.1
application.author=Tobias

# The default profile is used when no specific one is given
spring.profiles.default=test

# Auth: Base64 encoded secret is required with Spring Boot 3+ [Hint: The Matrix wisdom]
# Generate by either:
# $ echo -n "my-secret-key" | base64
# $ openssl rand -base64 64
jwt.secret=45LvCLkCIl+3okzy9/WQUFLQQkHLWAJNCiLFGfqZetZOjG5DbLcbI90fIhqgNPkLMERCRoXnluPZQGCRdyicfg==
